name: Deploy to Cloud Run

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Authenticate with Google Cloud
              uses: google-github-actions/auth@v1
              with:
                  credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

            - name: Authenticate Docker with GCR
              run: |
                  gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

            - name: Create file
              run: |
                  echo ALLOWED_ORIGIN=${{ secrets.ALLOWED_ORIGIN }} > ./app/.env
                  echo BACKEND_API_URL=${{ secrets.BACKEND_API_URL }} >> ./app/.env
                  echo GCS_PRIVATE_BUCKET_NAME=${{ secrets.GCS_PRIVATE_BUCKET_NAME }} >> ./app/.env
                  echo GCS_JSON_PATH=${{ secrets.GCS_JSON_PATH }} >> ./app/.env
                  echo NODE_ENV=${{ secrets.NODE_ENV }} >> ./app/.env
                  echo GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} >> ./app/.env
                  mkdir -p ./app/${{ secrets.GCS_SERVICE_ACCOUNT_DIR }}
                  echo ${{ secrets.GCS_SERVICE_ACCOUNT_KEY }} >> ./app/${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

            - name: Setup Google Cloud SDK
              uses: google-github-actions/setup-gcloud@v1
              with:
                  project_id: ${{ secrets.GCP_PROJECT_ID }}
                  service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

            # - name: Verify IAM Policy
            #   run: |
            #     gcloud projects get-iam-policy ${{ secrets.GCP_PROJECT_ID }} \
            #       --flatten="bindings[].members" \
            #       --format="table(bindings.role)" \
            #       --filter="bindings.members:serviceAccount:${{ secrets.GCP_SERVICE_ACCOUNT_KEY_NAME }}@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"

            - name: Build and push Docker image
              run: |
                  docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPO_NAME }}/${{ secrets.APP_NAME }} .
                  docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPO_NAME }}/${{ secrets.APP_NAME }}

            - name: Deploy to Cloud Run
              run: |
                  gcloud run deploy ${{ secrets.APP_NAME }} \
                    --image ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPO_NAME }}/${{ secrets.APP_NAME }} \
                    --region ${{ secrets.GCP_REGION }} \
                    --platform managed \
                    --allow-unauthenticated
